// Mocks generated by mockito. Do not edit. Use `flutter test --update-goldens` or `flutter test update-goldens` or hand-edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:mockito/mockito.dart' as _i1;
import 'package:signsync/services/permissions_service.dart' as _i2;

class _FakePermissionsService_0 extends _i1.SmartFake implements _i2.PermissionsService {
  _FakePermissionsService_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PermissionsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPermissionsService extends _i1.Mock implements _i2.PermissionsService {
  MockPermissionsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.PermissionStatus get cameraStatus => (super.noSuchMethod(
        Invocation.getter(#cameraStatus),
        returnValue: _FakePermissionsService_0(
          this,
          Invocation.getter(#cameraStatus),
        ),
      ) as _i2.PermissionStatus);
  @override
  _i2.PermissionStatus get microphoneStatus => (super.noSuchMethod(
        Invocation.getter(#microphoneStatus),
        returnValue: _FakePermissionsService_0(
          this,
          Invocation.getter(#microphoneStatus),
        ),
      ) as _i2.PermissionStatus);
  @override
  _i2.PermissionStatus get photoLibraryStatus => (super.noSuchMethod(
        Invocation.getter(#photoLibraryStatus),
        returnValue: _FakePermissionsService_0(
          this,
          Invocation.getter(#photoLibraryStatus),
        ),
      ) as _i2.PermissionStatus);
  @override
  _i2.PermissionStatus get notificationStatus => (super.noSuchMethod(
        Invocation.getter(#notificationStatus),
        returnValue: _FakePermissionsService_0(
          this,
          Invocation.getter(#notificationStatus),
        ),
      ) as _i2.PermissionStatus);
  @override
  int get cameraRequestCount => (super.noSuchMethod(
        Invocation.getter(#cameraRequestCount),
        returnValue: 0,
      ) as int);
  @override
  int get microphoneRequestCount => (super.noSuchMethod(
        Invocation.getter(#microphoneRequestCount),
        returnValue: 0,
      ) as int);
  @override
  _i2.PermissionStatus get overallStatus => (super.noSuchMethod(
        Invocation.getter(#overallStatus),
        returnValue: _FakePermissionsService_0(
          this,
          Invocation.getter(#overallStatus),
        ),
      ) as _i2.PermissionStatus);
  @override
  bool get allPermissionsGranted => (super.noSuchMethod(
        Invocation.getter(#allPermissionsGranted),
        returnValue: false,
      ) as bool);
  @override
  bool get hasCameraPermission => (super.noSuchMethod(
        Invocation.getter(#hasCameraPermission),
        returnValue: false,
      ) as bool);
  @override
  bool get hasMicrophonePermission => (super.noSuchMethod(
        Invocation.getter(#hasMicrophonePermission),
        returnValue: false,
      ) as bool);
  @override
  bool get hasPhotoLibraryPermission => (super.noSuchMethod(
        Invocation.getter(#hasPhotoLibraryPermission),
        returnValue: false,
      ) as bool);
  @override
  Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: Future<void>.value(),
        returnValueForMissingStub: Future<void>.value(),
      ) as Future<void>);
  @override
  Future<bool> requestCameraPermission() => (super.noSuchMethod(
        Invocation.method(
          #requestCameraPermission,
          [],
        ),
        returnValue: Future<bool>.value(false),
        returnValueForMissingStub: Future<bool>.value(false),
      ) as Future<bool>);
  @override
  Future<bool> requestMicrophonePermission() => (super.noSuchMethod(
        Invocation.method(
          #requestMicrophonePermission,
          [],
        ),
        returnValue: Future<bool>.value(false),
        returnValueForMissingStub: Future<bool>.value(false),
      ) as Future<bool>);
  @override
  Future<bool> requestPhotoLibraryPermission() => (super.noSuchMethod(
        Invocation.method(
          #requestPhotoLibraryPermission,
          [],
        ),
        returnValue: Future<bool>.value(false),
        returnValueForMissingStub: Future<bool>.value(false),
      ) as Future<bool>);
  @override
  Future<bool> requestNotificationPermission() => (super.noSuchMethod(
        Invocation.method(
          #requestNotificationPermission,
          [],
        ),
        returnValue: Future<bool>.value(false),
        returnValueForMissingStub: Future<bool>.value(false),
      ) as Future<bool>);
  @override
  Future<Map<dynamic, dynamic>> requestAllPermissions() => (super.noSuchMethod(
        Invocation.method(
          #requestAllPermissions,
          [],
        ),
        returnValue: Future<Map<dynamic, dynamic>>.value(<dynamic, dynamic>{}),
        returnValueForMissingStub: Future<Map<dynamic, dynamic>>.value(<dynamic, dynamic>{}),
      ) as Future<Map<dynamic, dynamic>>);
  @override
  Future<void> openSettings() => (super.noSuchMethod(
        Invocation.method(
          #openSettings,
          [],
        ),
        returnValue: Future<void>.value(),
        returnValueForMissingStub: Future<void>.value(),
      ) as Future<void>);
  @override
  Future<bool> isPermissionGranted(dynamic permission) => (super.noSuchMethod(
        Invocation.method(
          #isPermissionGranted,
          [permission],
        ),
        returnValue: Future<bool>.value(false),
        returnValueForMissingStub: Future<bool>.value(false),
      ) as Future<bool>);
  @override
  Future<bool> shouldShowRationale(dynamic permission) => (super.noSuchMethod(
        Invocation.method(
          #shouldShowRationale,
          [permission],
        ),
        returnValue: Future<bool>.value(false),
        returnValueForMissingStub: Future<bool>.value(false),
      ) as Future<bool>);
  @override
  void resetRetryCounters() => super.noSuchMethod(
        Invocation.method(
          #resetRetryCounters,
          [],
        ),
      );
  @override
  Future<String> getPermissionRationale(String? permissionType) => (super.noSuchMethod(
        Invocation.method(
          #getPermissionRationale,
          [permissionType],
        ),
        returnValue: Future<String>.value(''),
        returnValueForMissingStub: Future<String>.value(''),
      ) as Future<String>);
}
